#!/usr/bin/env bash

echo "Sourcing functions"
source $HOME/.config/herbstluftwm/variables
source $HOME/.config/herbstluftwm/helpers/hc.sh
source $HOME/.config/herbstluftwm/helpers/monitorStuff.sh

echo "Setting up monitors"
source $HOME/.config/herbstluftwm/monitorSetup

hc emit_hook reload

echo "Running global pre-setup"
source $HOME/.config/herbstluftwm/specifics/global_pre

echo "Loading Base Settings"
source $HOME/.config/herbstluftwm/settings

echo "Setting Keybinds"
source $HOME/.config/herbstluftwm/keybinds

echo "Loading Theme"
source $HOME/.config/herbstluftwm/theme

# unlock, just to be sure
hc unlock

echo "Running global post-setup"
source $HOME/.config/herbstluftwm/specifics/global_post
tryExecute "$HOME/.config/herbstluftwm/specifics/${HOSTNAME}_post"

if hc silent ! get_attr my_not_first_autostart ; then
    echo "Setting up floating tag"
    source ~/.config/herbstluftwm/helpers/floatmon.sh
    $HOME/.config/herbstluftwm/helpers/floatingFocusFix.sh &
fi

killall -q compton
while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
compton &
