#!/bin/bash

cmds=()

hc() {
    cmds+=(";" "$@")
}

hc emit_hook reload

xsetroot -solid '#222222'
hc keyunbind --all

#herbstclient detect_monitors
hc detect_monitors
#hc set_monitors 2560x1080+0+0 1680x1050+2560+0
hc pad 0 30 0 30 0

Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-c       close_and_remove
hc keybind $Mod-Return spawn ${TERMINAL:-terminator} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Alt-l spawn dm-tool lock

hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right


hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right


hc keybind $Mod-u chain .-. split bottom 0.5 .-. focus down
hc keybind $Mod-o chain .-. split right  0.5 .-. focus right

hc keybind $Mod-Shift-u chain .-. split bottom 0.5 .-. shift_edge down
hc keybind $Mod-Shift-o chain .-. split right  0.5 .-. shift_edge right

hc keybind $Mod-Control-space split explode


resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-w set_layout max
hc keybind $Mod-g set_layout grid
hc keybind $Mod-v set_layout vertical
hc keybind $Mod-a set_layout horizontal
hc keybind $Mod-Shift-space cycle_layout
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-d spawn rofi -show run


# Volume
hc keybind XF86AudioRaiseVolume spawn pulseaudio-ctl up
hc keybind XF86AudioLowerVolume spawn pulseaudio-ctl down
hc keybind XF86AudioMute spawn pulseaudio-ctl mute

# Brightness

hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#ff9933'
hc set frame_border_normal_color '#322322'
hc set frame_bg_normal_color '#292a44'
hc set frame_bg_active_color '#292a44'
hc set frame_border_width 2
hc set always_show_frame 0
hc set frame_active_opacity 0
hc set frame_normal_opacity 0
hc set frame_transparent_width 0

hc attr theme.active.color '#ffffff'
hc attr theme.normal.color '#000000'
hc attr theme.urgent.color '#e72d2d'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set window_padding 0
hc set frame_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# tags (Font-Awesome)
TAG_NAMES=( {"     ","     ","     ","     ","     ","     ","     ","     ","     "} )
#TAG_NAMES=( {" WEB "," TERMINALS "," DEV "," MUSIC "," FILES "," CHAT "," VMs "," NEWS "," SCHOOL "," OTHER "} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key"        use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'[Pp]olybar' manage=off
hc rule class=Spotify tag=
hc rule class=firefox tag=

hc unlock

herbstclient chain "${cmds[@]}" &

herbstclient set tree_style '╾│ ├└╼─┐'

pkill compton
compton -b
killall dunst
dunst -conf /home/audron/.config/dunst/dunstrc &
nitrogen --restore &
xrdb .Xresources
pkill polybar
polybar top &
polybar bot &
pkill redshift
redshift-gtk -t 5600K:3500K &
xmodmap ~/.xmodmap &
NetworkManager &
nm-applet &

if herbstclient silent new_attr bool my_not_first_autostart ; then
    mopidy &
fi

