#!/bin/sh

CONF_DIR="$HOME/.config/sway"

# Load utility functions and config vars
. "$CONF_DIR/functions"

# Main Settings
# -------------
 
mod="Mod4"
terminal="alacritty"
menu="wofi --show drun"

# -------------

# Load config
source "$CONF_DIR/conf.d/input"
source "$CONF_DIR/conf.d/keybinds"
source "$CONF_DIR/conf.d/theme"

# Load Host specific setup
[ -f "$CONF_DIR/specifics/$(hostname -f)" ] && . "$CONF_DIR/specifics/$(hostname -f)"

launch waybar &
launch wlsunset -t 3500 -T 5600 -l 50.1 -L 8.6 -g 0.9 &
