#!/usr/bin/env bash

help() {
    echo "kubectl debug netshoot [-h | -e [POD]] ([ARG] ...)"
    echo ""
    echo "Options:"
    echo "  --help: this help message"
    echo "  -h: use host networking for the pod"
    echo "  -n: atttach to specific node"
    echo "  -e [POD]: attach to an existing pod using kubectl debug"
}

while [[ $# -gt 0 ]] && [[ "$1" == "-"* ]] ;
do
    opt="$1";
    shift;              #expose next argument
    case "$opt" in
        "--" ) break 2;;
        "--help" ) help;;
        "-e" )
            EPHEMERAL=1;;
        "-h" )
            HOST_NET=1;;
        "-n" )
            NODE=$1
	    shift;;
        *) continue;;
   esac
done

netshoot() {
    kubectl run "netshoot-$RANDOM" --rm -i --tty --image nicolaka/netshoot "$@"
    exit 0
}

ephemeral() {
    POD="$1"
    shift 1
    kubectl debug "$POD" -it --image=nicolaka/netshoot "$@"
    exit 0
}

if [ -n "$HOST_NET" ]; then
    HOST_ARG=--overrides='{"spec": {"hostNetwork": true}}'
fi

if [ -n "$NODE" ]; then
    NODE_ARG=--overrides="{\"spec\": {\"nodeSelector\": {\"kubernetes.io/hostname\": \"$NODE\"}}}"
fi

set -x

if [ -n "$EPHEMERAL" ]; then
    ephemeral ${HOST_ARG:+"$HOST_ARG"} ${NODE_ARG:+"$NODE_ARG"} "$@"
else
    netshoot ${HOST_ARG:+"$HOST_ARG"} ${NODE_ARG:+"$NODE_ARG"} "$@"
fi
