#!/usr/bin/env bash
#
#

if [[ "$1" == "help" || "$1" == "--help" ]]
then
    echo "kubectl ssh ([NAME] ...)"
    echo "  SSH's to the nodes given as NAME using tmux-cssh."
    echo "  If no names are given then all nodes are targeted."
    echo ""
    echo "Options:"
    echo "  --help: This help page"
    echo "  -e: Use ExternalIP to connect to node instead of InternalIP"
    exit 0
fi

set -x

TYPE="InternalIP"

if [[ "$1" == "-e" ]]
then
    TYPE="ExternalIP"
    shift 1
fi

get_ip() {
    kubectl get nodes -o jsonpath="{.status.addresses[?(@.type == '$TYPE')].address}" "$@"
}

get_ips() {
    kubectl get nodes -o jsonpath="{.items[*].status.addresses[?(@.type == '$TYPE')].address}" "$@"
}

if [[ "$@" =~ ( |\') || ! "$@" ]]
then
    NODES=$(get_ips "$@")
else
    NODES=$(get_ip "$@")
fi

tmux-cssh $NODES
