{ config, lib, pkgs, ... }:

{
  programs.zsh.plugins = [{
    # will source zsh-autosuggestions.plugin.zsh
    name = "powerlevel10k";
    file = "powerlevel10k.zsh-theme";
    src = pkgs.fetchFromGitHub {
      owner = "romkatv";
      repo = "powerlevel10k";
      rev = "v1.16.1";
      hash = "sha256:0fkfh8j7rd8mkpgz6nsx4v7665d375266shl1aasdad8blgqmf0c";
    };
  }];

  programs.zsh.sessionVariables = {
    POWERLEVEL9K_MODE = "nerdfont-fontconfig";
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS = [ "dir" "vcs" "virtualenv" ];
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS = [
      "status"
      "kubecontext"
      "root_indicator"
      "background_jobs"
      "command_execution_time"
    ];
    POWERLEVEL9K_HOST_TEMPLATE = "`hostname -f`";
    POWERLEVEL9K_SHORTEN_DIR_LENGTH = 2;
    POWERLEVEL9K_SHORTEN_DELIMITER = "";
    POWERLEVEL9K_SHORTEN_STRATEGY = "truncate_from_right";
    POWERLEVEL9K_PROMPT_ON_NEWLINE = true;
    POWERLEVEL9K_PROMPT_ADD_NEWLINE = true;
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD = 1;
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT = "d h m s";

    POWERLEVEL9K_INSTANT_PROMPT = "quiet";

    POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND =
      "kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|kc|tk";
    POWERLEVEL9K_KUBECONTEXT_FOREGROUND = "yellow";
    POWERLEVEL9K_KUBECONTEXT_BACKGROUND = "235";

    POWERLEVEL9K_DIR_DEFAULT_BACKGROUND = "236";
    POWERLEVEL9K_DIR_HOME_BACKGROUND = "236";
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND = "236";
    POWERLEVEL9K_DIR_HOME_FOREGROUND = "yellow";
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND = "yellow";
    POWERLEVEL9K_DIR_DEFAULT_FOREGROUND = "yellow";
    POWERLEVEL9K_VCS_CLEAN_BACKGROUND = "235";
    POWERLEVEL9K_VCS_CLEAN_FOREGROUND = "yellow";
    POWERLEVEL9K_VCS_MODIFIED_BACKGROUND = "235";
    POWERLEVEL9K_VCS_MODIFIED_FOREGROUND = "yellow";
    POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND = "235";
    POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND = "yellow";
    POWERLEVEL9K_HOST_LOCAL_BACKGROUND = "236";
    POWERLEVEL9K_HOST_LOCAL_FOREGROUND = "yellow";
    POWERLEVEL9K_HOST_REMOTE_BACKGROUND = "003";
    POWERLEVEL9K_HOST_REMOTE_FOREGROUND = "232";
    POWERLEVEL9K_STATUS_OK_BACKGROUND = "234";
    POWERLEVEL9K_STATUS_ERROR_BACKGROUND = "001";
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND = "235";
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND = "yellow";

    #Icon config;
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX = "%K{white}%k";
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX = " %F{yellow}%f ";

    POWERLEVEL9K_VCS_GIT_ICON = " ";
    POWERLEVEL9K_VCS_GIT_GITHUB_ICON = " ";
    POWERLEVEL9K_VCS_GIT_GITLAB_ICON = " ";
    POWERLEVEL9K_VCS_BRANCH_ICON = " ";
    POWERLEVEL9K_VCS_STAGED_ICON = "";
    POWERLEVEL9K_VCS_UNSTAGED_ICON = "";
    POWERLEVEL9K_VCS_UNTRACKED_ICON = "";
    POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON = "";
    POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON = "";

    POWERLEVEL9K_HOME_ICON = "";
    POWERLEVEL9K_HOME_SUB_ICON = "";
    POWERLEVEL9K_FOLDER_ICON = "";
    POWERLEVEL9K_EXECUTION_TIME_ICON = "";
    POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR = "";
    POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR = "";
  };
}
