#!/bin/sh

# Essentials
c bindsym "$mod+Return" exec "$terminal"
c bindsym "$mod+r" exec "$menu"
c bindsym "$mod+c" kill

c floating_modifier "$mod" normal

# Exit and reload
c bindsym "$mod+Shift+r" reload
c bindsym "$mod+Shift+e" exec "swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'"

# Movement
c bindsym "$mod+h" focus left
c bindsym "$mod+j" focus down
c bindsym "$mod+k" focus up
c bindsym "$mod+l" focus right

c bindsym "$mod+Shift+h" move left
c bindsym "$mod+Shift+j" move down
c bindsym "$mod+Shift+k" move up
c bindsym "$mod+Shift+l" move right

for i in $(seq 0 9); do
    c bindsym "$mod+$i" workspace number "$i"
    c bindsym "$mod+Shift+$i" move container to workspace number "$i"
done

# Layout stuff
c bindsym "$mod+n" splith
c bindsym "$mod+m" splitv

# Switch the current container between different layout styles
# bindsym $mod+s layout stacking
c bindsym "$mod+w" layout tabbed
c bindsym "$mod+t" layout toggle split
c bindsym "$mod+f" fullscreen
c bindsym "$mod+s" floating toggle
c bindsym "$mod+space" focus mode_toggle
c bindsym "$mod+a" focus parent

# Sway has a "scratchpad", which is a bag of holding for windows.
# You can send windows there and get them back later.

# Move the currently focused window to the scratchpad
c bindsym "$mod+Shift+minus" move scratchpad

# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
c bindsym "$mod+minus" scratchpad show
