# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let kvmfr = pkgs.unstable.linuxKernel.packages.linux_xanmod_latest.kvmfr.overrideAttrs (prev: {
      version = "B5-413-eb1774f9";
      src = pkgs.fetchFromGitHub {
        owner = "gnif";
        repo = "LookingGlass";
        rev = "eb1774f955eb194220e3d51ae320b6a0d56eb131";
        sha256 = "sha256-CPBrIBw7oCs5v4kmoQ9f1iuWML6uueOLEmaNKh2tI44=";
        fetchSubmodules = true;
      };

      patches = [];
    });
in {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  services.udev.extraRules = ''
    SUBSYSTEM=="kvmfr", OWNER="audron", GROUP="users", MODE="0666"
  '';

  boot = {
    zfs.forceImportRoot = false;

    initrd = {
      availableKernelModules =
        [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };

    kernelPackages = pkgs.linuxKernel.packages.linux_xanmod_latest;

    kernelModules = [ "kvm-amd" "amdgpu" "zfs" "kvmfr" ];
    extraModulePackages =
      [ kvmfr ];


    extraModprobeConfig = ''
      options kvmfr static_size_mb=256
    '';

    # Use the systemd-boot EFI boot loader.
    supportedFilesystems = [ "zfs" ];
    zfs.devNodes = "/dev/";

    loader = {
      efi = { canTouchEfiVariables = true; };

      # Use the GRUB 2 boot loader.
      grub = {
        enable = true;
        version = 2;
        zfsSupport = true;
        efiSupport = true;
        device = "nodev";

        # Force this list to only contain these entries
        # by default /boot is in here too, breaking my setup
        mirroredBoots = lib.mkForce [
          {
            devices = [ "/dev/nvme0n1" ];
            path = "/boot/1";
          }
          {
            devices = [ "/dev/nvme1n1" ];
            path = "/boot/2";
          }
        ];

        memtest86.enable = true;
      };
    };
  };

  services.zfs = {
    trim.enable = true;
    autoScrub = {
      enable = true;
      pools = [ "rpool" ];
    };
  };

  fileSystems."/" = {
    device = "rpool/root";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/nix" = {
    device = "rpool/root/nix";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/etc" = {
    device = "rpool/root/etc";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/home" = {
    device = "rpool/root/home";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/srv" = {
    device = "rpool/root/srv";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/var" = {
    device = "rpool/root/var";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/var/lib" = {
    device = "rpool/root/var/lib";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/var/lib/containers" = {
    device = "rpool/root/var/lib/containers";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/var/log" = {
    device = "rpool/root/var/log";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/var/spool" = {
    device = "rpool/root/var/spool";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/boot/1" = {
    device = "/dev/disk/by-id/nvme-WDS100T1X0E-00AFY0_2152BE442809-part2";
    fsType = "vfat";
    options = [ "X-mount.mkdir" ];
  };

  fileSystems."/boot/2" = {
    device = "/dev/disk/by-id/nvme-WDS100T1X0E-00AFY0_2152BE442510-part2";
    fsType = "vfat";
    options = [ "X-mount.mkdir" ];
  };

  hardware.cpu.amd.updateMicrocode = false;
  hardware.video.hidpi.enable = true;
}
