#!/bin/bash

for m in $(polybar --list-monitors | cut -d":" -f1); do
    if [[ $m == "DP-4.8" ]]; then
      MONITOR=$m polybar --reload one &
    elif [[ $m == "DVI-D-0" ]]; then
      MONITOR=$m polybar --reload two &
    fi
done
