#!/usr/bin/env zsh
source $HOME/.zsh/plugins/romkatv/powerlevel10k/powerlevel10k.zsh-theme

# Configure powerlevel stuff
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs virtualenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs host)
POWERLEVEL9K_HOST_TEMPLATE="`hostname -f`"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='236'
POWERLEVEL9K_DIR_HOME_BACKGROUND='236'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='236'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='002'
POWERLEVEL9K_DIR_HOME_FOREGROUND='002'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='002'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='002'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='235'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='002'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='235'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='002'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='235'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='002'
POWERLEVEL9K_HOST_LOCAL_BACKGROUND='236'
POWERLEVEL9K_HOST_LOCAL_FOREGROUND='002'
POWERLEVEL9K_HOST_REMOTE_BACKGROUND='003'
POWERLEVEL9K_HOST_REMOTE_FOREGROUND='232'
POWERLEVEL9K_STATUS_OK_BACKGROUND='235'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='001'

#Icon config
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=$'%K{white}%k'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=$' %F{002}\uf101%f '

POWERLEVEL9K_VCS_GIT_ICON=$'\uf1d2 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uf113 '
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$'\uf296 '
POWERLEVEL9K_VCS_BRANCH_ICON=$' '
POWERLEVEL9K_VCS_STAGED_ICON=$'\uf633'
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\uf62f'
POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\uf659'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$'\uf175'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$'\uf176'

POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
#POWERLEVEL9K_STATUS_OK_ICON='\UF2B0'
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=' '
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\UE0BA'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' '
