#!/bin/sh

CONF_DIR="$HOME/.config/bspwm"

# Load utility functions and config vars
. "$CONF_DIR/functions"
. "$CONF_DIR/config"

# Load Host specific setup
[ -f "$CONF_DIR/specifics/$(hostname -f)" ] && . "$CONF_DIR/specifics/$(hostname -f)"

# Start Polybar
kill_running polybar
export BAR_BOTTOM=true
for m in $(polybar --list-monitors | cut -d":" -f1); do
      MONITOR=$m polybar --reload -l error all &
done

launch sxhkd &
# launch picom &
