#!/bin/sh

# Load utility functions and config vars
. ./functions
. ./config

# Load Host specific setup
. "./specifics/$(hostname -f)"

# Start Polybar
kill_running polybar
for m in $(polybar --list-monitors | cut -d":" -f1); do
      MONITOR=$m polybar --log=error --reload all &
done

launch sxhkd &
launch picom -d :0 &
