#!/bin/sh

CONF_DIR="$HOME/.config/bspwm"

# Load utility functions and config vars
. "$CONF_DIR/functions"
. "$CONF_DIR/config"

# Load Host specific setup
[ -f "$CONF_DIR/specifics/$(hostname -f)" ] && . "$CONF_DIR/specifics/$(hostname -f)"

# Start Polybar
kill_running polybar
for m in $(polybar --list-monitors | cut -d":" -f1); do
      MONITOR=$m polybar --log=error --reload all &
done

launch sxhkd &
launch picom &
