#!/bin/sh

config focus_follows_pointer true

config border_width         1
config window_gap          12

config split_ratio          0.52
config borderless_monocle   true
config gapless_monocle      true
