#!/bin/sh

alias config="bspc config"

config focus_follows_pointer true
config pointer_follows_focus false

config presel_feedback false

config focused_border_color \#E88A30

config border_width         1
config window_gap          12

config split_ratio          0.52
config borderless_monocle   true
config gapless_monocle      true
